# https://help.github.com/articles/customizing-css-and-html-in-your-jekyll-theme/

theme: jekyll-theme-cayman

# https://github.com/pages-themes/cayman/blob/master/_layouts/default.html
title: Software Technology that Deals with Deeper Memory Hierarchy in Post-petascale Era

github:
  is_project_page: false
